export const ALL_ANIMAL_REQUEST = "ALL_ANIMAL_REQUEST";
export const ALL_ANIMAL_SUCCESS = "ALL_ANIMAL_SUCCESS";
export const ALL_ANIMAL_FAIL = "ALL_ANIMAL_FAIL";

export const LOAD_MORE_ANIMAL_REQUEST = "LOAD_MORE_ANIMAL_REQUEST";
export const LOAD_MORE_ANIMAL_SUCCESS = "LOAD_MORE_ANIMAL_SUCCESS";
export const LOAD_MORE_ANIMAL_FAIL = "LOAD_MORE_ANIMAL_FAIL";
export const QUERIES = "QUERIES";

export const ADMIN_ANIMAL_REQUEST = "ADMIN_ANIMAL_REQUEST";
export const ADMIN_ANIMAL_SUCCESS = "ADMIN_ANIMAL_SUCCESS";
export const ADMIN_ANIMAL_FAIL = "ADMIN_ANIMAL_FAIL";

export const NEW_ANIMAL_REQUEST = "NEW_ANIMAL_REQUEST";
export const NEW_ANIMAL_SUCCESS = "NEW_ANIMAL_SUCCESS";
export const NEW_ANIMAL_RESET = "NEW_ANIMAL_RESET";
export const NEW_ANIMAL_FAIL = "NEW_ANIMAL_FAIL";

export const UPDATE_ANIMAL_REQUEST = "UPDATE_ANIMAL_REQUEST";
export const UPDATE_ANIMAL_SUCCESS = "UPDATE_ANIMAL_SUCCESS";
export const UPDATE_ANIMAL_RESET = "UPDATE_ANIMAL_RESET";
export const UPDATE_ANIMAL_FAIL = "UPDATE_ANIMAL_FAIL";

export const DELETE_ANIMAL_REQUEST = "DELETE_ANIMAL_REQUEST";
export const DELETE_ANIMAL_SUCCESS = "DELETE_ANIMAL_SUCCESS";
export const DELETE_ANIMAL_RESET = "DELETE_ANIMAL_RESET";
export const DELETE_ANIMAL_FAIL = "DELETE_ANIMAL_FAIL";

export const ANIMAL_DETAILS_REQUEST = "ANIMAL_DETAILS_REQUEST";
export const ANIMAL_DETAILS_SUCCESS = "ANIMAL_DETAILS_SUCCESS";
export const ANIMAL_DETAILS_FAIL = "ANIMAL_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
