const buffaloBreedsArr = [
  {
    id: 0,
    name: "मुर्रा",
    value: "मुर्रा",
    // value:"murrah",
    check: false,
  },
  {
    id: 1,
    name: "हरयावली भैंस",
    value: "हरयावली भैंस",
    check: false,
  },
  {
    id: 2,
    name: "देसी भैंस",
    value: "देसी भैंस",
    check: false,
  },
  {
    id: 3,
    name: "काली",
    value: "काली",
    check: false,
  },
  {
    id: 4,
    name: "कुण्डी",
    value: "कुण्डी",
    check: false,
  },
  {
    id: 5,
    name: "जफरराबादी",
    value: "जफरराबादी",
    check: false,
  },

  {
    id: 6,
    name: "बन्नी",
    value: "बन्नी",
    check: false,
  },
  {
    id: 7,
    name: "कुम्भी",
    value: "कुम्भी",
    check: false,
  },
  {
    id: 8,
    name: "कुन्नि",
    value: "कुन्नि",
    check: false,
  },
  {
    id: 9,
    name: "नीली रावी",
    value: "नीली रावी",
    check: false,
  },
  {
    id: 10,
    name: "भदावरी",
    value: "भदावरी",
    check: false,
  },
  {
    id: 11,
    name: "गुजरती भैंस",
    value: "गुजरती भैंस",
    check: false,
  },

  {
    id: 12,
    name: "गोदावरी",
    value: "गोदावरी",
    check: false,
  },
  {
    id: 13,
    name: "सुरति",
    value: "सुरति",
    check: false,
  },
  {
    id: 14,
    name: "मेहसाणा",
    value: "मेहसाणा",
    check: false,
  },
  {
    id: 15,
    name: "पंढरपुरी",
    value: "पंढरपुरी",
    check: false,
  },
  {
    id: 16,
    name: "नागपुरी",
    check: false,
  },
];

const cowBreedsArr = [
  {
    id: 17,
    name: "गिर",
    value: "गिर",
    check: false,
  },
  {
    id: 18,
    name: "साहीवाल",
    value: "साहीवाल",
    check: false,
  },
  {
    id: 19,
    name: "देसी गाये",
    value: "देसी गाये",
    check: false,
  },
  {
    id: 20,
    name: "होल्सटीन फ्रीशि",
    value: "होल्सटीन फ्रीशि",
    check: false,
  },
  {
    id: 21,
    name: "जर्सी",
    value: "जर्सी",
    check: false,
  },
  {
    id: 22,
    name: "अमेरिकन",
    value: "अमेरिकन",
    check: false,
  },
  {
    id: 23,
    name: "दोगली",
    value: "दोगली",
    check: false,
  },
  {
    id: 24,
    name: "राठी",
    value: "राठी",
    check: false,
  },
  {
    id: 25,
    name: "थारपारकर",
    value: "थारपारकर",
    check: false,
  },
  {
    id: 26,
    name: "हरियावली गाये",
    value: "हरियावली गाये",
    check: false,
  },

  {
    id: 27,
    name: "मारवाड़ी",
    value: "मारवाड़ी",
    check: false,
  },
  {
    id: 28,
    name: "कांकरेज",
    value: "कांकरेज",
    check: false,
  },
  {
    id: 29,
    name: "कपिला",
    value: "कपिला",
    check: false,
  },
  {
    id: 30,
    name: "आयरशायर",
    value: "आयरशायर",
    check: false,
  },

  {
    id: 31,
    name: "हरधेनु",
    value: "हरधेनु",
    check: false,
  },
  {
    id: 32,
    name: "नागोरी",
    value: "नागोरी",
    check: false,
  },
  {
    id: 33,
    name: "गुजराती गाये",
    value: "गुजराती गाये",
    check: false,
  },

  {
    id: 34,
    name: "रेड सिंधी",
    value: "रेड सिंधी",
    check: false,
  },
  {
    id: 35,
    name: "देवनी",
    value: "देवनी",
    check: false,
  },
  {
    id: 36,
    name: "रेड डेन",
    value: "रेड डेन",
    check: false,
  },
  {
    id: 37,
    name: "ब्राउन स्विस",
    value: "ब्राउन स्विस",
    check: false,
  },

  {
    id: 38,
    name: "सांचोरी ",
    value: "सांचोरी ",
    check: false,
  },
  {
    id: 39,
    name: "मालवी",
    value: "मालवी",
    check: false,
  },
];
const animalCategoryArr = ["भैंस", "गाय", "भैंसा", "बैल"];

// const arr2 = [
//       "मुर्रा",
//       "हरयावली भैंस",
//       "देसी भैंस",
//       "काली",
//       "कुण्डी",
//       "जफरराबादी",
//       "बन्नी",
//       "कुम्भी",
//       "कुन्नि",
//       "नीली रावी",
//       "भदावरी",
//       "गुजरती भैंस",
//       "गोदावरी",
//       "सुरति",
//       "मेहसाणा",
//       "पंढरपुरी",
//       "नागपुरी",
//       "गिर",
//       "साहीवाल",
//       "देसी गाये",
//       "होल्सटीन फ्रीशियन",
//       "जर्सी",
//       "अमेरिकन",
//       "दोगली",
//       "राठी",
//       "थारपारकर",
//       "हरियावली गाये",
//       "मारवाड़ी",
//       "कांकरेज",
//       "कपिला",
//       "आयरशायर",
//       "हरधेनु",
//       "नागोरी",
//       "गुजराती गाये",
//       "रेड सिंधी",
//       "देवनी",
//       "रेड डेन",
//       "ब्राउन स्विस",
//       "सांचोरी ",
//       "मालवी",
//     ];

const otherAnimalCategoryArr = [
  "Horse",
  "goat",
  "malegoat",
  "horsefemale",
  "malehorse",
];

const breedsArr = [
  "Murrah",
  "Haryani",
  "Desi",
  "Kali",
  "Kundi",
  "Jaffrabadi",
  "Banni",
  "Kumbbi",
  "Kunni",
  "Nili Ravi",
  "Bhandawari",
  "Gujrati",
  "Godhawari",
  "Surti",
  "Mehrana",
  "Pandharpuri",
  "Nagpuri",
  "Gir",
  "Sahival",
  "Desi Gay",
  "Hafestiesian",
  "Jersey",
  "American",
  "Dogali",
  "Rathi",
  "Tharparkar",
  "Haryani Gay",
  "Marwari",
  "Kankrey",
  "Kapila",
  "Ayrshire",
  "Hardhenu",
  "Nagori",
  "Gujrati Gay",
  "Res sindhi",
  "Deoni",
  "Red Dane",
  "Brown swiss",
  "Sanchori",
  "Malvi",
];

export {
  cowBreedsArr,
  buffaloBreedsArr,
  animalCategoryArr,
  otherAnimalCategoryArr,
  breedsArr,
};
